"""initial schema

Revision ID: 0001_initial_schema
Revises: 
Create Date: 2026-07-12 06:57:25.046249+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0001_initial_schema'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # pgvector extension for RAG vector tables added by later issues.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_trace',
    sa.Column('trace_id', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('agent_name', sa.String(), nullable=False),
    sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('llm_model', sa.String(), nullable=True),
    sa.Column('llm_tokens_used', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('trace_id', name=op.f('pk_agent_trace'))
    )
    op.create_index(op.f('ix_agent_trace_event_id'), 'agent_trace', ['event_id'], unique=False)
    op.create_table('data_quality_error',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(), nullable=True),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('error_category', sa.String(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_quality_error'))
    )
    op.create_index(op.f('ix_data_quality_error_event_id'), 'data_quality_error', ['event_id'], unique=False)
    op.create_table('event_audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('from_status', sa.String(), nullable=True),
    sa.Column('to_status', sa.String(), nullable=True),
    sa.Column('operator', sa.String(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_audit_log'))
    )
    op.create_index(op.f('ix_event_audit_log_event_id'), 'event_audit_log', ['event_id'], unique=False)
    op.create_table('event_context_field_version',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('event_id', 'field_name', name=op.f('pk_event_context_field_version'))
    )
    op.create_table('event_context_journal',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_context_journal')),
    sa.UniqueConstraint('event_id', 'field_name', 'version', name='uq_event_context_journal_field_version')
    )
    op.create_index(op.f('ix_event_context_journal_event_id'), 'event_context_journal', ['event_id'], unique=False)
    op.create_table('llm_call_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('agent_name', sa.String(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('fallback_level', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_call_log'))
    )
    op.create_index(op.f('ix_llm_call_log_event_id'), 'llm_call_log', ['event_id'], unique=False)
    op.create_table('security_event',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('final_verdict', sa.String(), nullable=False),
    sa.Column('entities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('creation_source_ref', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_reference_snapshots', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('current_primary_source_record_id', sa.String(), nullable=True),
    sa.Column('disposition_source_ref', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('disposition_policy', sa.String(), nullable=False),
    sa.Column('raw_alert_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_alert_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replan_count', sa.Integer(), nullable=False),
    sa.Column('degraded_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('escalated', sa.Boolean(), nullable=False),
    sa.Column('external_unsynced', sa.Boolean(), nullable=False),
    sa.Column('event_context_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('event_id', name=op.f('pk_security_event'))
    )
    op.create_index(op.f('ix_security_event_status'), 'security_event', ['status'], unique=False)
    op.create_table('source_connector',
    sa.Column('connector_id', sa.String(), nullable=False),
    sa.Column('source_product', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('device_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('read_endpoint', sa.String(), nullable=True),
    sa.Column('disposition_endpoint', sa.String(), nullable=True),
    sa.Column('capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('disposition_policy_default', sa.String(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('watermark', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('schema_version', sa.String(), nullable=False),
    sa.Column('read_credential_ref', sa.String(), nullable=True),
    sa.Column('disposition_credential_ref', sa.String(), nullable=True),
    sa.Column('connector_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('connector_id', name=op.f('pk_source_connector'))
    )
    op.create_table('tool_call_log',
    sa.Column('call_id', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('action_id', sa.String(), nullable=True),
    sa.Column('tool_name', sa.String(), nullable=False),
    sa.Column('tool_category', sa.String(), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('call_id', name=op.f('pk_tool_call_log'))
    )
    op.create_index(op.f('ix_tool_call_log_event_id'), 'tool_call_log', ['event_id'], unique=False)
    op.create_table('action',
    sa.Column('action_id', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('plan_revision', sa.Integer(), nullable=False),
    sa.Column('action_fingerprint', sa.String(), nullable=False),
    sa.Column('action_category', sa.String(), nullable=False),
    sa.Column('action_name', sa.String(), nullable=False),
    sa.Column('tool_name', sa.String(), nullable=False),
    sa.Column('action_level', sa.String(), nullable=False),
    sa.Column('execution_phase', sa.String(), nullable=False),
    sa.Column('activation_condition', sa.String(), nullable=True),
    sa.Column('approved_operation_template_hash', sa.String(), nullable=True),
    sa.Column('approved_terminal_dispositions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('target_type', sa.String(), nullable=True),
    sa.Column('target', sa.String(), nullable=True),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('auto_execute', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('impact_assessment', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('playbook_id', sa.String(), nullable=True),
    sa.Column('provider_name', sa.String(), nullable=True),
    sa.Column('execution_owner', sa.String(), nullable=True),
    sa.Column('execution_job_id', sa.String(), nullable=True),
    sa.Column('tool_call_id', sa.String(), nullable=True),
    sa.Column('idempotency_key', sa.String(), nullable=True),
    sa.Column('writeback_required', sa.Boolean(), nullable=False),
    sa.Column('writeback_applicable', sa.Boolean(), nullable=False),
    sa.Column('writeback_readiness', sa.String(), nullable=False),
    sa.Column('writeback_block_reason', sa.String(), nullable=True),
    sa.Column('writeback_status', sa.String(), nullable=True),
    sa.Column('disposition_source_ref', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('superseded_by_revision', sa.Integer(), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effect_verification_status', sa.String(), nullable=True),
    sa.Column('rollback_status', sa.String(), nullable=True),
    sa.Column('source_action_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['security_event.event_id'], name=op.f('fk_action_event_id_security_event')),
    sa.PrimaryKeyConstraint('action_id', name=op.f('pk_action')),
    sa.UniqueConstraint('action_fingerprint', name='uq_action_action_fingerprint')
    )
    op.create_index(op.f('ix_action_event_id'), 'action', ['event_id'], unique=False)
    op.create_index('ix_action_idempotency_key', 'action', ['idempotency_key'], unique=False)
    op.create_table('evidence',
    sa.Column('evidence_id', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('evidence_type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('related_entities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_ref', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('mitre_technique', sa.String(), nullable=True),
    sa.Column('is_conflicting', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['security_event.event_id'], name=op.f('fk_evidence_event_id_security_event')),
    sa.PrimaryKeyConstraint('evidence_id', name=op.f('pk_evidence'))
    )
    op.create_index(op.f('ix_evidence_event_id'), 'evidence', ['event_id'], unique=False)
    op.create_table('report',
    sa.Column('report_id', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('sections', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('final_verdict', sa.String(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('generated_by', sa.String(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['security_event.event_id'], name=op.f('fk_report_event_id_security_event')),
    sa.PrimaryKeyConstraint('report_id', name=op.f('pk_report'))
    )
    op.create_index(op.f('ix_report_event_id'), 'report', ['event_id'], unique=False)
    op.create_table('source_object',
    sa.Column('source_record_id', sa.String(), nullable=False),
    sa.Column('source_product', sa.String(), nullable=False),
    sa.Column('source_tenant_id', sa.String(), nullable=False),
    sa.Column('connector_id', sa.String(), nullable=False),
    sa.Column('source_kind', sa.String(), nullable=False),
    sa.Column('source_object_id', sa.String(), nullable=False),
    sa.Column('source_object_type', sa.String(), nullable=True),
    sa.Column('parent_source_object_id', sa.String(), nullable=True),
    sa.Column('source_status_raw', sa.String(), nullable=True),
    sa.Column('source_disposition', sa.String(), nullable=False),
    sa.Column('source_concurrency_token', sa.String(), nullable=True),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('schema_version', sa.String(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_payload_hash', sa.String(), nullable=True),
    sa.Column('normalized', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('current_source_status_raw', sa.String(), nullable=True),
    sa.Column('current_source_disposition', sa.String(), nullable=False),
    sa.Column('current_concurrency_token', sa.String(), nullable=True),
    sa.Column('source_sync_state', sa.String(), nullable=True),
    sa.Column('next_outbox_sequence', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['source_connector.connector_id'], name=op.f('fk_source_object_connector_id_source_connector')),
    sa.PrimaryKeyConstraint('source_record_id', name=op.f('pk_source_object')),
    sa.UniqueConstraint('source_product', 'source_tenant_id', 'connector_id', 'source_kind', 'source_object_id', name='uq_source_object_identity')
    )
    op.create_index(op.f('ix_source_object_connector_id'), 'source_object', ['connector_id'], unique=False)
    op.create_table('action_execution_job',
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('action_id', sa.String(), nullable=False),
    sa.Column('provider_name', sa.String(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('provider_job_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('claimed_by', sa.String(), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('poll_after_ms', sa.Integer(), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.String(), nullable=True),
    sa.Column('provider_message', sa.Text(), nullable=True),
    sa.Column('raw_result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['action.action_id'], name=op.f('fk_action_execution_job_action_id_action')),
    sa.ForeignKeyConstraint(['event_id'], ['security_event.event_id'], name=op.f('fk_action_execution_job_event_id_security_event')),
    sa.PrimaryKeyConstraint('job_id', name=op.f('pk_action_execution_job'))
    )
    op.create_index(op.f('ix_action_execution_job_action_id'), 'action_execution_job', ['action_id'], unique=False)
    op.create_index(op.f('ix_action_execution_job_event_id'), 'action_execution_job', ['event_id'], unique=False)
    op.create_index('ix_action_execution_job_idempotency_key', 'action_execution_job', ['idempotency_key'], unique=False)
    op.create_index('ix_action_execution_job_status', 'action_execution_job', ['status'], unique=False)
    op.create_table('disposition_outbox',
    sa.Column('outbox_id', sa.String(), nullable=False),
    sa.Column('writeback_id', sa.String(), nullable=False),
    sa.Column('disposition_id', sa.String(), nullable=False),
    sa.Column('action_id', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('closure_cycle', sa.Integer(), nullable=False),
    sa.Column('source_record_id', sa.String(), nullable=False),
    sa.Column('source_locator_hash', sa.String(), nullable=False),
    sa.Column('source_sequence', sa.BigInteger(), nullable=False),
    sa.Column('intent_kind', sa.String(), nullable=False),
    sa.Column('logical_slot', sa.String(), nullable=False),
    sa.Column('supersedes_disposition_id', sa.String(), nullable=True),
    sa.Column('superseded_by_disposition_id', sa.String(), nullable=True),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('command_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('command_payload_sha256', sa.String(), nullable=False),
    sa.Column('delivery_status', sa.String(), nullable=False),
    sa.Column('latest_writeback_status', sa.String(), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_by', sa.String(), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_code', sa.String(), nullable=True),
    sa.Column('last_error_detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['action.action_id'], name=op.f('fk_disposition_outbox_action_id_action')),
    sa.ForeignKeyConstraint(['event_id'], ['security_event.event_id'], name=op.f('fk_disposition_outbox_event_id_security_event')),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_object.source_record_id'], name=op.f('fk_disposition_outbox_source_record_id_source_object')),
    sa.PrimaryKeyConstraint('outbox_id', name=op.f('pk_disposition_outbox')),
    sa.UniqueConstraint('idempotency_key', name='uq_disposition_outbox_idempotency_key'),
    sa.UniqueConstraint('source_record_id', 'source_sequence', name='uq_disposition_outbox_source_sequence')
    )
    op.create_index(op.f('ix_disposition_outbox_action_id'), 'disposition_outbox', ['action_id'], unique=False)
    op.create_index('ix_disposition_outbox_delivery_status', 'disposition_outbox', ['delivery_status'], unique=False)
    op.create_index('ix_disposition_outbox_disposition_id', 'disposition_outbox', ['disposition_id'], unique=False)
    op.create_index(op.f('ix_disposition_outbox_event_id'), 'disposition_outbox', ['event_id'], unique=False)
    op.create_index('ix_disposition_outbox_latest_writeback_status', 'disposition_outbox', ['latest_writeback_status'], unique=False)
    op.create_index('ix_disposition_outbox_lease_expires_at', 'disposition_outbox', ['lease_expires_at'], unique=False)
    op.create_index('ix_disposition_outbox_next_retry_at', 'disposition_outbox', ['next_retry_at'], unique=False)
    op.create_index(op.f('ix_disposition_outbox_source_record_id'), 'disposition_outbox', ['source_record_id'], unique=False)
    op.create_index(op.f('ix_disposition_outbox_writeback_id'), 'disposition_outbox', ['writeback_id'], unique=False)
    op.create_index('uq_disposition_outbox_event_status_active_head', 'disposition_outbox', ['action_id', 'closure_cycle', 'intent_kind', 'logical_slot'], unique=True, postgresql_where=sa.text("superseded_by_disposition_id IS NULL AND intent_kind = 'event_status_update'"))
    op.create_table('disposition_receipt',
    sa.Column('writeback_id', sa.String(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('disposition_id', sa.String(), nullable=False),
    sa.Column('action_id', sa.String(), nullable=False),
    sa.Column('source_record_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('confirmation_evidence', sa.String(), nullable=True),
    sa.Column('provider_record_id', sa.String(), nullable=True),
    sa.Column('provider_job_id', sa.String(), nullable=True),
    sa.Column('provider_code', sa.String(), nullable=True),
    sa.Column('provider_message', sa.Text(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('target_results', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('truncated', sa.Boolean(), nullable=False),
    sa.Column('simulated', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['action.action_id'], name=op.f('fk_disposition_receipt_action_id_action')),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_object.source_record_id'], name=op.f('fk_disposition_receipt_source_record_id_source_object')),
    sa.PrimaryKeyConstraint('writeback_id', 'sequence', name=op.f('pk_disposition_receipt'))
    )
    op.create_index(op.f('ix_disposition_receipt_action_id'), 'disposition_receipt', ['action_id'], unique=False)
    op.create_index(op.f('ix_disposition_receipt_disposition_id'), 'disposition_receipt', ['disposition_id'], unique=False)
    op.create_index(op.f('ix_disposition_receipt_source_record_id'), 'disposition_receipt', ['source_record_id'], unique=False)
    op.create_table('source_event_link',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source_record_id', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('promotion_status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['security_event.event_id'], name=op.f('fk_source_event_link_event_id_security_event')),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_object.source_record_id'], name=op.f('fk_source_event_link_source_record_id_source_object')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_event_link')),
    sa.UniqueConstraint('source_record_id', 'event_id', name='uq_source_event_link_pair')
    )
    op.create_index(op.f('ix_source_event_link_event_id'), 'source_event_link', ['event_id'], unique=False)
    op.create_index(op.f('ix_source_event_link_source_record_id'), 'source_event_link', ['source_record_id'], unique=False)
    op.create_table('action_target_result',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('canonical_target', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('artifact_id', sa.String(), nullable=True),
    sa.Column('raw_result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['action_execution_job.job_id'], name=op.f('fk_action_target_result_job_id_action_execution_job')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_action_target_result'))
    )
    op.create_index(op.f('ix_action_target_result_job_id'), 'action_target_result', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_action_target_result_job_id'), table_name='action_target_result')
    op.drop_table('action_target_result')
    op.drop_index(op.f('ix_source_event_link_source_record_id'), table_name='source_event_link')
    op.drop_index(op.f('ix_source_event_link_event_id'), table_name='source_event_link')
    op.drop_table('source_event_link')
    op.drop_index(op.f('ix_disposition_receipt_source_record_id'), table_name='disposition_receipt')
    op.drop_index(op.f('ix_disposition_receipt_disposition_id'), table_name='disposition_receipt')
    op.drop_index(op.f('ix_disposition_receipt_action_id'), table_name='disposition_receipt')
    op.drop_table('disposition_receipt')
    op.drop_index('uq_disposition_outbox_event_status_active_head', table_name='disposition_outbox', postgresql_where=sa.text("superseded_by_disposition_id IS NULL AND intent_kind = 'event_status_update'"))
    op.drop_index(op.f('ix_disposition_outbox_writeback_id'), table_name='disposition_outbox')
    op.drop_index(op.f('ix_disposition_outbox_source_record_id'), table_name='disposition_outbox')
    op.drop_index('ix_disposition_outbox_next_retry_at', table_name='disposition_outbox')
    op.drop_index('ix_disposition_outbox_lease_expires_at', table_name='disposition_outbox')
    op.drop_index('ix_disposition_outbox_latest_writeback_status', table_name='disposition_outbox')
    op.drop_index(op.f('ix_disposition_outbox_event_id'), table_name='disposition_outbox')
    op.drop_index('ix_disposition_outbox_disposition_id', table_name='disposition_outbox')
    op.drop_index('ix_disposition_outbox_delivery_status', table_name='disposition_outbox')
    op.drop_index(op.f('ix_disposition_outbox_action_id'), table_name='disposition_outbox')
    op.drop_table('disposition_outbox')
    op.drop_index('ix_action_execution_job_status', table_name='action_execution_job')
    op.drop_index('ix_action_execution_job_idempotency_key', table_name='action_execution_job')
    op.drop_index(op.f('ix_action_execution_job_event_id'), table_name='action_execution_job')
    op.drop_index(op.f('ix_action_execution_job_action_id'), table_name='action_execution_job')
    op.drop_table('action_execution_job')
    op.drop_index(op.f('ix_source_object_connector_id'), table_name='source_object')
    op.drop_table('source_object')
    op.drop_index(op.f('ix_report_event_id'), table_name='report')
    op.drop_table('report')
    op.drop_index(op.f('ix_evidence_event_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index('ix_action_idempotency_key', table_name='action')
    op.drop_index(op.f('ix_action_event_id'), table_name='action')
    op.drop_table('action')
    op.drop_index(op.f('ix_tool_call_log_event_id'), table_name='tool_call_log')
    op.drop_table('tool_call_log')
    op.drop_table('source_connector')
    op.drop_index(op.f('ix_security_event_status'), table_name='security_event')
    op.drop_table('security_event')
    op.drop_index(op.f('ix_llm_call_log_event_id'), table_name='llm_call_log')
    op.drop_table('llm_call_log')
    op.drop_index(op.f('ix_event_context_journal_event_id'), table_name='event_context_journal')
    op.drop_table('event_context_journal')
    op.drop_table('event_context_field_version')
    op.drop_index(op.f('ix_event_audit_log_event_id'), table_name='event_audit_log')
    op.drop_table('event_audit_log')
    op.drop_index(op.f('ix_data_quality_error_event_id'), table_name='data_quality_error')
    op.drop_table('data_quality_error')
    op.drop_index(op.f('ix_agent_trace_event_id'), table_name='agent_trace')
    op.drop_table('agent_trace')
    # ### end Alembic commands ###
